L,basicpp_entry_point,7,1,1
L,_err_filefree_get_key,-1,0,0
L,_err_eof_get_key,-1,0,0
L,_err_divzero_get_key,-1,0,0
L,_err_fp_get_key,-1,0,0
L,redo,20,1,0
L,exit,380,1,0
L,exit2,405,1,0
L,_endf_0,-1,0,1
L,_endfc_0,411,1,1
L,_err_filefree_dcf_sync,-1,0,0
L,_err_eof_dcf_sync,-1,0,0
L,_err_divzero_dcf_sync,-1,0,0
L,_err_fp_dcf_sync,-1,0,0
L,_endf_1,-1,0,1
L,_endfc_1,480,1,1
L,_err_filefree_initrollotimetable,-1,0,0
L,_err_eof_initrollotimetable,-1,0,0
L,_err_divzero_initrollotimetable,-1,0,0
L,_err_fp_initrollotimetable,-1,0,0
L,_endf_2,-1,0,1
L,_endfc_2,691,1,1
L,_err_filefree_updaterollos,-1,0,0
L,_err_eof_updaterollos,-1,0,0
L,_err_divzero_updaterollos,-1,0,0
L,_err_fp_updaterollos,-1,0,0
L,_endf_3,-1,0,1
L,_endfc_3,949,1,1
L,_err_filefree_getrolloautomaticstate,-1,0,0
L,_err_eof_getrolloautomaticstate,-1,0,0
L,_err_divzero_getrolloautomaticstate,-1,0,0
L,_err_fp_getrolloautomaticstate,-1,0,0
L,_endf_4,-1,0,1
L,_endfc_4,1004,1,1
L,_err_filefree_setrolloautomaticstate,-1,0,0
L,_err_eof_setrolloautomaticstate,-1,0,0
L,_err_divzero_setrolloautomaticstate,-1,0,0
L,_err_fp_setrolloautomaticstate,-1,0,0
L,_endf_5,-1,0,1
L,_endfc_5,1059,1,1
L,_err_filefree_menushowupdowntimes,-1,0,0
L,_err_eof_menushowupdowntimes,-1,0,0
L,_err_divzero_menushowupdowntimes,-1,0,0
L,_err_fp_menushowupdowntimes,-1,0,0
L,_endf_6,-1,0,1
L,_endfc_6,1415,1,1
L,_err_filefree_menusetrolloautomatic,-1,0,0
L,_err_eof_menusetrolloautomatic,-1,0,0
L,_err_divzero_menusetrolloautomatic,-1,0,0
L,_err_fp_menusetrolloautomatic,-1,0,0
L,_endf_7,-1,0,1
L,_endfc_7,1846,1,1
L,_err_filefree_menumanualupdown,-1,0,0
L,_err_eof_menumanualupdown,-1,0,0
L,_err_divzero_menumanualupdown,-1,0,0
L,_err_fp_menumanualupdown,-1,0,0
L,_endf_8,-1,0,1
L,_endfc_8,2123,1,1
L,_err_filefree_updaterelaisio,-1,0,0
L,_err_eof_updaterelaisio,-1,0,0
L,_err_divzero_updaterelaisio,-1,0,0
L,_err_fp_updaterelaisio,-1,0,0
L,_endf_9,-1,0,1
L,_endfc_9,2269,1,1
L,_err_filefree_setrelaisstate,-1,0,0
L,_err_eof_setrelaisstate,-1,0,0
L,_err_divzero_setrelaisstate,-1,0,0
L,_err_fp_setrelaisstate,-1,0,0
L,_endf_10,-1,0,1
L,_endfc_10,2532,1,1
L,_err_filefree_getrelaisstate,-1,0,0
L,_err_eof_getrelaisstate,-1,0,0
L,_err_divzero_getrelaisstate,-1,0,0
L,_err_fp_getrelaisstate,-1,0,0
L,_endf_11,-1,0,1
L,_endfc_11,2777,1,1
L,_err_filefree_relaisimpulse,-1,0,0
L,_err_eof_relaisimpulse,-1,0,0
L,_err_divzero_relaisimpulse,-1,0,0
L,_err_fp_relaisimpulse,-1,0,0
L,_endf_12,-1,0,1
L,_endfc_12,2914,1,1
L,_err_filefree___relaisio_updaterelais,-1,0,0
L,_err_eof___relaisio_updaterelais,-1,0,0
L,_err_divzero___relaisio_updaterelais,-1,0,0
L,_err_fp___relaisio_updaterelais,-1,0,0
L,_endf_13,-1,0,1
L,_endfc_13,2991,1,1
L,_err_filefree_showtime,-1,0,0
L,_err_eof_showtime,-1,0,0
L,_err_divzero_showtime,-1,0,0
L,_err_fp_showtime,-1,0,0
L,_endf_14,-1,0,1
L,_endfc_14,3104,1,1
L,_err_filefree_showdowstring,-1,0,0
L,_err_eof_showdowstring,-1,0,0
L,_err_divzero_showdowstring,-1,0,0
L,_err_fp_showdowstring,-1,0,0
L,_endf_15,-1,0,1
L,_endfc_15,3217,1,1
L,_err_filefree_showdate,-1,0,0
L,_err_eof_showdate,-1,0,0
L,_err_divzero_showdate,-1,0,0
L,_err_fp_showdate,-1,0,0
L,_endf_16,-1,0,1
L,_endfc_16,3293,1,1
L,_err_filefree_calculatesunsin,-1,0,0
L,_err_eof_calculatesunsin,-1,0,0
L,_err_divzero_calculatesunsin,-1,0,0
L,_err_fp_calculatesunsin,-1,0,0
L,_endf_17,-1,0,1
L,_endfc_17,3415,1,1
L,_err_filefree_issummertime,-1,0,0
L,_err_eof_issummertime,-1,0,0
L,_err_divzero_issummertime,-1,0,0
L,_err_fp_issummertime,-1,0,0
L,_endf_18,-1,0,1
L,_endfc_18,3525,1,1
L,_err_filefree___timetablecalccos,-1,0,0
L,_err_eof___timetablecalccos,-1,0,0
L,_err_divzero___timetablecalccos,-1,0,0
L,_err_fp___timetablecalccos,-1,0,0
L,_endf_19,-1,0,1
L,_endfc_19,3707,1,1
L,_err_filefree_getrandvalue,-1,0,0
L,_err_eof_getrandvalue,-1,0,0
L,_err_divzero_getrandvalue,-1,0,0
L,_err_fp_getrandvalue,-1,0,0
L,_endf_20,-1,0,1
L,_endfc_20,3762,1,1
L,_err_filefree_calculatenextdowntime,-1,0,0
L,_err_eof_calculatenextdowntime,-1,0,0
L,_err_divzero_calculatenextdowntime,-1,0,0
L,_err_fp_calculatenextdowntime,-1,0,0
L,_endf_21,-1,0,1
L,_endfc_21,3855,1,1
L,_err_filefree_calculatenextuptime,-1,0,0
L,_err_eof_calculatenextuptime,-1,0,0
L,_err_divzero_calculatenextuptime,-1,0,0
L,_err_fp_calculatenextuptime,-1,0,0
L,_endf_22,-1,0,1
L,_endfc_22,3948,1,1
L,_err_filefree_dcftest,-1,0,0
L,_err_eof_dcftest,-1,0,0
L,_err_divzero_dcftest,-1,0,0
L,_err_fp_dcftest,-1,0,0
L,dcftest_start,3992,1,0
L,dcftest_display_bar_graph,4032,1,0
L,dcftest_signal_received,4168,1,0
L,_endf_23,-1,0,1
L,_endfc_23,4197,1,1
L,_next_0,-1,0,1
L,_exitfor_0,690,1,1
L,_next_1,-1,0,1
L,_exitfor_1,948,1,1
L,_next_2,-1,0,1
L,_exitfor_2,1369,1,1
L,_do_exit_0,1388,1,1
L,_do_exit_1,1547,1,1
L,_next_3,-1,0,1
L,_exitfor_3,1715,1,1
L,_next_4,-1,0,1
L,_exitfor_4,1785,1,1
L,_do_exit_2,1819,1,1
L,_next_5,-1,0,1
L,_exitfor_5,2077,1,1
L,_do_exit_3,2096,1,1
L,_next_6,-1,0,1
L,_exitfor_6,2188,1,1
L,_next_7,-1,0,1
L,_exitfor_7,2268,1,1
L,_next_8,-1,0,1
L,_exitfor_8,2887,1,1
L,_next_9,-1,0,1
L,_exitfor_9,4082,1,1
L,_do_exit_4,4456,1,1
L,_next_10,-1,0,1
L,_exitfor_10,4637,1,1
L,_do_exit_5,-1,0,1
F,get_key,15,1,1
F,dcf_sync,414,1,1
F,initrollotimetable,488,1,1
F,updaterollos,694,1,1
F,getrolloautomaticstate,952,1,1
F,setrolloautomaticstate,1007,1,1
F,menushowupdowntimes,1062,1,1
F,menusetrolloautomatic,1418,1,1
F,menumanualupdown,1849,1,1
F,updaterelaisio,2191,1,1
F,setrelaisstate,2272,1,1
F,getrelaisstate,2535,1,1
F,relaisimpulse,2780,1,1
F,__relaisio_updaterelais,2917,1,1
F,showtime,2994,1,1
F,showdowstring,3107,1,1
F,showdate,3220,1,1
F,calculatesunsin,3296,1,1
F,issummertime,3418,1,1
F,__timetablecalccos,3528,1,1
F,getrandvalue,3710,1,1
F,calculatenextdowntime,3765,1,1
F,calculatenextuptime,3858,1,1
F,dcftest,3951,1,1
V,port[1],7,-1,0,1,0,-1,0,-1
V,port[2],7,-1,0,1,0,-1,0,-1
V,port[3],7,-1,0,1,0,-1,0,-1
V,port[4],7,-1,0,1,0,-1,0,-1
V,port[5],7,-1,0,1,0,-1,0,-1
V,port[6],7,-1,0,1,0,-1,0,-1
V,port[7],7,-1,0,1,0,-1,0,-1
V,port[8],7,-1,0,1,0,-1,0,-1
V,port[9],7,-1,0,1,0,-1,0,-1
V,port[10],7,-1,0,1,0,-1,0,-1
V,port[11],7,-1,0,1,0,-1,0,-1
V,port[12],7,-1,0,1,0,-1,0,-1
V,port[13],7,-1,0,1,0,-1,0,-1
V,port[14],7,-1,0,1,0,-1,0,-1
V,port[15],7,-1,0,1,0,-1,0,-1
V,port[16],7,-1,0,1,0,-1,0,-1
V,byteport[1],11,-1,0,1,0,-1,0,-1
V,byteport[2],11,-1,0,1,0,-1,0,-1
V,wordport,10,-1,0,1,0,-1,0,-1
V,ad[1],8,-1,0,1,0,-1,0,-1
V,ad[2],8,-1,0,1,0,-1,0,-1
V,ad[3],8,-1,0,1,0,-1,0,-1
V,ad[4],8,-1,0,1,0,-1,0,-1
V,ad[5],8,-1,0,1,0,-1,0,-1
V,ad[6],8,-1,0,1,0,-1,0,-1
V,ad[7],8,-1,0,1,0,-1,0,-1
V,ad[8],8,-1,0,1,0,-1,0,-1
V,da[1],9,-1,0,1,0,-1,0,-1
V,da[2],9,-1,0,1,0,-1,0,-1
V,_ret,1,0:2,1,1,0,-1,0,-1
V,_sx1p,1,-1,0,1,0,-1,0,-1
V,_sx2p,1,-1,0,1,0,-1,0,-1
V,_sx1,1,-1,0,1,0,-1,0,-1
V,_sx2,1,-1,0,1,0,-1,0,-1
V,_sx3,1,-1,0,1,0,-1,0,-1
V,_sa,0,0,1,1,0,-1,0,-1
V,_sb,0,1,1,1,0,-1,0,-1
V,_sc,0,2,1,1,0,-1,0,-1
V,_sd,0,3,1,1,0,-1,0,-1
V,_se,0,-1,0,1,0,-1,0,-1
V,_sf,0,-1,0,1,0,-1,0,-1
V,FPACC1EX,0,0,1,0,0,-1,0,-1
V,FPACC1MN,0,1,1,0,0,-1,0,-1
V,MANT1LO,1,2:2,1,0,0,-1,0,-1
V,FPACC1MN1,0,2,1,0,0,-1,0,-1
V,FPACC1MN2,0,3,1,0,0,-1,0,-1
V,MANTSGN1,0,4,1,0,0,-1,0,-1
V,FPACC2EX,0,5,1,0,0,-1,0,-1
V,FPACC2MN,0,6,1,0,0,-1,0,-1
V,FPACC2MN1,0,7,1,0,0,-1,0,-1
V,FPACC2MN2,0,8,1,0,0,-1,0,-1
V,MANTSGN2,0,9,1,0,0,-1,0,-1
V,EXPSIGN,0,10,1,0,0,-1,0,-1
V,PWR10EXP,0,11,1,0,0,-1,0,-1
V,V0,0,12,1,0,0,-1,0,-1
V,V1,0,13,1,0,0,-1,0,-1
V,V2,0,14,1,0,0,-1,0,-1
V,V3,0,15,1,0,0,-1,0,-1
V,_sx3p,0,-1,0,0,0,-1,0,-1
V,backlight,7,15,1,0,0,-1,0,-1
V,dcfpower,9,0,1,0,0,-1,0,-1
V,index1,0,21,1,0,0,-1,0,-1
V,_get_key_adc8,8,7,1,0,0,-1,0,-1
V,_get_key_keycode,0,42,1,0,0,-1,0,-1
V,_get_key_buffer,0,43,1,0,0,-1,0,-1
V,_dcf_sync_conf1,0,44,1,0,0,-1,0,-1
V,_dcf_sync_sync,12,17.0,1,0,0,-1,0,-1
V,rollodisableautomatic,0,45,1,0,0,-1,0,-1
V,holidaymode,12,-1,0,0,0,-1,0,-1
V,minutessincemidnight,1,26:2,1,0,0,-1,0,-1
V,timetable,6,66:37,1,0,1,-1,37,-1
V,_timetable_1,0,66:37,1,1,1,70,37,0
V,_timetable_2,0,67:37,1,1,1,70,37,1
V,_timetable_3,0,68:37,1,1,1,70,37,2
V,_timetable_4,0,69:37,1,1,1,70,37,3
V,_timetable_5,0,70:37,1,1,1,70,37,4
V,_timetable_6,0,71:37,1,1,1,70,37,5
V,_timetable_7,0,72:37,1,1,1,70,37,6
V,_timetable_8,0,73:37,1,1,1,70,37,7
V,_timetable_9,0,74:37,1,1,1,70,37,8
V,_timetable_10,0,75:37,1,1,1,70,37,9
V,_timetable_11,0,76:37,1,1,1,70,37,10
V,_timetable_12,0,77:37,1,1,1,70,37,11
V,_timetable_13,0,78:37,1,1,1,70,37,12
V,_timetable_14,0,79:37,1,1,1,70,37,13
V,_timetable_15,0,80:37,1,1,1,70,37,14
V,_timetable_16,0,81:37,1,1,1,70,37,15
V,_timetable_17,0,82:37,1,1,1,70,37,16
V,_timetable_18,0,83:37,1,1,1,70,37,17
V,_timetable_19,0,84:37,1,1,1,70,37,18
V,_timetable_20,0,85:37,1,1,1,70,37,19
V,_timetable_21,0,86:37,1,1,1,70,37,20
V,_timetable_22,0,87:37,1,1,1,70,37,21
V,_timetable_23,0,88:37,1,1,1,70,37,22
V,_timetable_24,0,89:37,1,1,1,70,37,23
V,_timetable_25,0,90:37,1,1,1,70,37,24
V,_timetable_26,0,91:37,1,1,1,70,37,25
V,_timetable_27,0,92:37,1,1,1,70,37,26
V,_timetable_28,0,93:37,1,1,1,70,37,27
V,_timetable_29,0,94:37,1,1,1,70,37,28
V,_timetable_30,0,95:37,1,1,1,70,37,29
V,_timetable_31,0,96:37,1,1,1,70,37,30
V,_timetable_32,0,97:37,1,1,1,70,37,31
V,_timetable_33,0,98:37,1,1,1,70,37,32
V,_timetable_34,0,99:37,1,1,1,70,37,33
V,_timetable_35,0,100:37,1,1,1,70,37,34
V,_timetable_36,0,101:37,1,1,1,70,37,35
V,_timetable_37,0,102:37,1,1,1,70,37,36
V,timetableminutessincemidnight,0,46,1,0,0,-1,0,-1
V,timetablelastexecdayofmonth,0,47,1,0,0,-1,0,-1
V,rollo_index2,0,48,1,0,0,-1,0,-1
V,rollo_index3,0,49,1,0,0,-1,0,-1
V,_getrolloautomaticstate_index,0,50,1,0,0,-1,0,-1
V,_setrolloautomaticstate_index,0,51,1,0,0,-1,0,-1
V,_setrolloautomaticstate_state,12,17.1,1,0,0,-1,0,-1
V,menu_index1,0,52,1,0,0,-1,0,-1
V,menu_index2,0,-1,0,0,0,-1,0,-1
V,offset,0,53,1,0,0,-1,0,-1
V,_menumanualupdown_up,12,17.2,1,0,0,-1,0,-1
V,relaisio_sda,7,8,1,0,0,-1,0,-1
V,relaisio_scl,7,9,1,0,0,-1,0,-1
V,relaisio_internalrelais1port,7,28,1,0,0,-1,0,-1
V,relaisio_internalrelais2port,7,29,1,0,0,-1,0,-1
V,relaisio_internalrelais3port,7,30,1,0,0,-1,0,-1
V,relaisio_internalrelais4port,7,31,1,0,0,-1,0,-1
V,relaisio_externalrelais1port,7,0,1,0,0,-1,0,-1
V,relaisio_externalrelais2port,7,1,1,0,0,-1,0,-1
V,relaisio_externalrelais3port,7,2,1,0,0,-1,0,-1
V,relaisio_externalrelais4port,7,3,1,0,0,-1,0,-1
V,relaisio_externalrelais5port,7,4,1,0,0,-1,0,-1
V,relaisio_externalrelais6port,7,5,1,0,0,-1,0,-1
V,relaisio_externalrelais7port,7,6,1,0,0,-1,0,-1
V,relaisio_externalrelais8port,7,7,1,0,0,-1,0,-1
V,relaisio_externalrelais9port,12,17.3,1,0,0,-1,0,-1
V,relaisio_externalrelais10port,7,15,1,0,0,-1,0,-1
V,relaisio_led1port,7,24,1,0,0,-1,0,-1
V,relaisio_led2port,7,25,1,0,0,-1,0,-1
V,relaisio_led3port,7,26,1,0,0,-1,0,-1
V,relaisio_led4port,7,27,1,0,0,-1,0,-1
V,relaisio_internalrelaisstate,0,16,1,0,0,-1,0,-1
V,relaisio_internalrelais1state,12,16.0,1,0,0,139,0,-1
V,relaisio_internalrelais2state,12,16.1,1,0,0,139,0,-1
V,relaisio_internalrelais3state,12,16.2,1,0,0,139,0,-1
V,relaisio_internalrelais4state,12,16.3,1,0,0,139,0,-1
V,relaisio_externalrelaisstate,1,18:2,1,0,0,-1,0,-1
V,relaisio_externalrelais1state,12,18.0,1,0,0,144,0,-1
V,relaisio_externalrelais2state,12,18.1,1,0,0,144,0,-1
V,relaisio_externalrelais3state,12,18.2,1,0,0,144,0,-1
V,relaisio_externalrelais4state,12,18.3,1,0,0,144,0,-1
V,relaisio_externalrelais5state,12,18.4,1,0,0,144,0,-1
V,relaisio_externalrelais6state,12,18.5,1,0,0,144,0,-1
V,relaisio_externalrelais7state,12,18.6,1,0,0,144,0,-1
V,relaisio_externalrelais8state,12,18.7,1,0,0,144,0,-1
V,relaisio_externalrelais9state,12,19.0,1,0,0,144,0,-1
V,relaisio_externalrelais10state,12,19.1,1,0,0,144,0,-1
V,relaisio_turnofftimes,6,103:29,1,0,1,-1,29,-1
V,_relaisio_turnofftimes_1,0,103:29,1,1,1,155,29,0
V,_relaisio_turnofftimes_2,0,104:29,1,1,1,155,29,1
V,_relaisio_turnofftimes_3,0,105:29,1,1,1,155,29,2
V,_relaisio_turnofftimes_4,0,106:29,1,1,1,155,29,3
V,_relaisio_turnofftimes_5,0,107:29,1,1,1,155,29,4
V,_relaisio_turnofftimes_6,0,108:29,1,1,1,155,29,5
V,_relaisio_turnofftimes_7,0,109:29,1,1,1,155,29,6
V,_relaisio_turnofftimes_8,0,110:29,1,1,1,155,29,7
V,_relaisio_turnofftimes_9,0,111:29,1,1,1,155,29,8
V,_relaisio_turnofftimes_10,0,112:29,1,1,1,155,29,9
V,_relaisio_turnofftimes_11,0,113:29,1,1,1,155,29,10
V,_relaisio_turnofftimes_12,0,114:29,1,1,1,155,29,11
V,_relaisio_turnofftimes_13,0,115:29,1,1,1,155,29,12
V,_relaisio_turnofftimes_14,0,116:29,1,1,1,155,29,13
V,_relaisio_turnofftimes_15,0,117:29,1,1,1,155,29,14
V,_relaisio_turnofftimes_16,0,118:29,1,1,1,155,29,15
V,_relaisio_turnofftimes_17,0,119:29,1,1,1,155,29,16
V,_relaisio_turnofftimes_18,0,120:29,1,1,1,155,29,17
V,_relaisio_turnofftimes_19,0,121:29,1,1,1,155,29,18
V,_relaisio_turnofftimes_20,0,122:29,1,1,1,155,29,19
V,_relaisio_turnofftimes_21,0,123:29,1,1,1,155,29,20
V,_relaisio_turnofftimes_22,0,124:29,1,1,1,155,29,21
V,_relaisio_turnofftimes_23,0,125:29,1,1,1,155,29,22
V,_relaisio_turnofftimes_24,0,126:29,1,1,1,155,29,23
V,_relaisio_turnofftimes_25,0,127:29,1,1,1,155,29,24
V,_relaisio_turnofftimes_26,0,128:29,1,1,1,155,29,25
V,_relaisio_turnofftimes_27,0,129:29,1,1,1,155,29,26
V,_relaisio_turnofftimes_28,0,130:29,1,1,1,155,29,27
V,_relaisio_turnofftimes_29,0,131:29,1,1,1,155,29,28
V,relaisio_timervalue,0,54,1,0,0,-1,0,-1
V,relaisio_index1,0,55,1,0,0,-1,0,-1
V,relaisio_curtime,1,28:2,1,0,0,-1,0,-1
V,relaisio_oldtimervalue,1,30:2,1,0,0,-1,0,-1
V,_setrelaisstate_index,0,56,1,0,0,-1,0,-1
V,_setrelaisstate_state,12,17.4,1,0,0,-1,0,-1
V,_getrelaisstate_index,0,57,1,0,0,-1,0,-1
V,_relaisimpulse_index,0,58,1,0,0,-1,0,-1
V,_relaisimpulse_length,0,59,1,0,0,-1,0,-1
V,_showtime_withseconds,12,17.5,1,0,0,-1,0,-1
V,_showtime_blinkcolon,12,17.6,1,0,0,-1,0,-1
V,_showdate_withlongyear,12,17.7,1,0,0,-1,0,-1
V,wordvar,1,32:2,1,0,0,-1,0,-1
V,floatvar,16,22:4,1,0,0,-1,0,-1
V,_calculatesunsin_amplitude,1,34:2,1,0,0,-1,0,-1
V,_calculatesunsin_fortomorrow,12,20.0,1,0,0,-1,0,-1
V,_issummertime_tomorrow,12,20.1,1,0,0,-1,0,-1
V,_issummertime_calcday,0,60,1,0,0,-1,0,-1
V,___timetablecalccos_f,16,22:4,1,0,0,198,0,-1
V,_getrandvalue_groupindex,0,61,1,0,0,-1,0,-1
V,_calculatenextdowntime_groupindex,0,62,1,0,0,-1,0,-1
V,_calculatenextdowntime_fortomorrow,12,20.2,1,0,0,-1,0,-1
V,_calculatenextdowntime_res,1,36:2,1,0,0,-1,0,-1
V,_calculatenextuptime_groupindex,0,63,1,0,0,-1,0,-1
V,_calculatenextuptime_fortomorrow,12,20.3,1,0,0,-1,0,-1
V,_calculatenextuptime_res,1,38:2,1,0,0,-1,0,-1
V,loop,0,64,1,0,0,-1,0,-1
V,bar_graph_length,0,65,1,0,0,-1,0,-1
V,signal_monitor,1,40:2,1,0,0,-1,0,-1
